---
name: Release Charts
'on':
  push:
    branches:
    - 'pulsar-3.3.0-custom'
jobs:
  release:
    permissions:
      contents: write
      packages: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Add repositories
        run: |
          helm dependency add bitnami https://charts.bitnami.com/bitnami
          helm dependency add dysnix https://dysnix.github.io/charts/
          helm dependency add stable https://charts.bitnami.com/bitnami
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          charts_dir: "charts"
